### ISSUE TITLE
[Enhancement] Removing env vars and the user could change the makepkg mostly himself

### ISSUE THREAD

**Issue by ptTrR** [kevall474/linux-kernel#25]
Hey, 
I'm actually building the kernel, but missed many vars, which I've read in the "PKGBUILD" before. 
So, maybe go for one thing and not actually like it is, if you understand what I mean. 

Or provide a little config.yml for the configurable settings. I'm looking forward to your kernel, since it is finally something different too Linux tkg. Also, you provided mostly a nice documentation, and I did understand the different schedulers now. Additionally, you showed me two more of them. Nice to see. 

But most users don't want to build all 5 kernels for testing I think. Thats also a thing. 

But im looking forward, actually building muqss, if its worked correctly with the env. 
I'm going to fork this repo and maybe provide you a documentation. 

Regards.

**Comment by kevall474** [comment]
Thanks for the feedback. I will reintroduce  the variables as env variables so the user will be able to enable/disable with env _"variables" makepkg -s. And maybe provide more documentation for those variables.

The build.sh is mostly for myself because I have 24 cores CPU so the compile time is not very long and I do a lots of testing between the kernels. But user can run it if they are willing to.   

Thanks

**Comment by ptTrR** [comment]
Yeah, if you can compile that fast. Got just 6 T and 6 HT Cores. 
You're GCC-Optimatizion worked so far, with the provided script. Only telling because I'm running a 8700k which is called in the Script as CoffeLake, but they're running as skylake. Little weird. But the Script is working good. 

I've didn't reboot until now. When im rebooted, and tested it little bit, i can maybe tell you more. Just switched from PDS LINUX TKG to for testing. 
Also, as I said  didn't know where to edit these variables mostly, and it's not my first compile, but in the makepkg which is also like a documentation is confusing. 

Maybe create an "advanced-config.cfg" and config.cfg and getting from there the readings into your makepkg. Should be no problem. 

Feels like much "critic", but all in all your first feedback I think. Youve created in this project much work, and it will be create i think! :)

regards.

**Comment by kevall474** [comment]
I allready did some testing with an .cfg file and a script file, based on to work done by linux-tkg but with my old variables. Keep an eye on the repo and feel free to contribute.

**Comment by ptTrR** [comment]
Ill going to try to work it little out, when you pushed the fix with the .cfg  file with just basics in it.
I gonna work on a own Archarm 64 OS for my RPi, cause Arch itself did not worked out so far. 
Ill gonna take a watch, so im not using makepkg that much, so i didnt unserstand it really. 

When youre already written so much in about everything, then easy cusomatizon would be good for starters. 

Looking forward!

**Comment by kevall474** [comment]
I have a PKGBUILD on my computer with some commands like this;

plain "Choose your CPU Scheduler"
read -rp "`echo $' > 1.cachy\n > 2.cacule\n > 3.muqss\n > 4.bmq\n > 5.pds\n > Default (none)\nchoice[1-5]: '`" _cpu_sched; 

With little descriptions.

Ill try to make a little push this weekend in a test folder. I'm looking to add rc release in the options so I can delete my mainline-kernel repo and just have one repo for linux kernel builds.

I messed a little bit with some cross compile builds for arm64/raspberrypi kernel but It never come to a project. Will look at yours if it leads to a project.

Have a good day.

**Comment by ptTrR** [comment]
So, i finally rebooted from the muqqs kernel. compiled with gcc+llvm. 

My Network (LAN) didnt worked. Like the driver or something else wasnt loading. Weird. 
After using 5.9.14 Zen or 5.10.1 tkg pds it is working again. 

Maybe ill try another compile with the pds.

**Comment by kevall474** [comment]
Strange never had issues with the LAN drivers or WIFI drivers with my two computers with muqss or the others. What is the type of your network card? Since I use the config file from linux-zen it should build most of the needed drivers. Maybe take a look at the .config file make after the "make olddefconfig" command an if you dont see the driver you need maybe add a "scripts/config --enable "the driver" ... . I will take a look at that.

**Comment by ptTrR** [comment]
Yeah, me too. And i builded many TKG kernels :D. 
thats really weird. true.

Before i runned 5.10.1 ups from tkg. but that got some issues at booting and i didnt liked how my cpu performed there. idk. maybe my fails, at correctly configuring the kernel.

**Comment by ptTrR** [comment]
So ive compiled the pds kernel and that didnt boot anymore. maybe there is something in 5.10.1.

**Comment by kevall474** [comment]
Seems strange I boot correctly on my Ryzen 3900x computer and my Intel computer. Maybe try building the kernel with generic CPU option

**Comment by ptTrR** [comment]
is there a way to contact you that isnt mail? 
Maybe discord, irc, ..
And nice work these days!

**Comment by kevall474** [comment]
yes that is my email. Since I dont trust Microsoft or Gmail email services i use Tutanotamail and Protonmail

**Comment by ptTrR** [comment]
New Repo is working like a charm. 
Used it two times for 5.10.3 and 5.10.4 and cacule shed. 
Thanks for your work!
